name: Deploy to Amazon ECR and ECS

on:
  workflow_dispatch: 
      
env:
  AWS_REGION: us-east-2

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    env:
      ECR_REPOSITORY: thrive-demo
      ECS_SERVICE: ${{ vars.SERVICE }}-Service           
      ECS_CLUSTER: ${{ vars.SERVICEUPPERCASE }}             
      ECS_TASK_DEFINITION: devops/${{ vars.SERVICELOWERCASE }}-service-TD.json  
      CONTAINER_NAME_WEB: ${{ vars.SERVICELOWERCASE }}_django
      CONTAINER_NAME_PROXY: ${{ vars.SERVICELOWERCASE }}_nginx
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
